create database QI charset=utf8;
/* Drop Tables */
use QI;
DROP TABLE COMPUTER;
DROP TABLE INTERMEDIARY;
DROP TABLE NEWS;
DROP TABLE USER;




/* Create Tables */

CREATE TABLE COMPUTER
(
	COMPUTERNAME VARCHAR(20) NOT NULL,
	COMPUTERPRICE VARCHAR(20) NOT NULL,
	COMPUTERTYPE VARCHAR(20) NOT NULL,
	COMPUTERBIRTH VARCHAR(20) NOT NULL,
	COMPUTERCOLOR VARCHAR(15),
	PRIMARY KEY (COMPUTERNAME)
);


CREATE TABLE INTERMEDIARY
(
	INTERMEDIRYNAME VARCHAR(20) NOT NULL,
	INTERMEDIARYPHONENUMBER VARCHAR(20) NOT NULL,
	INTERMEDIARYCOMPUTERTYPE VARCHAR(20) NOT NULL,
	PRIMARY KEY (INTERMEDIRYNAME)
);


CREATE TABLE NEWS
(
	NEWSTITLE VARCHAR(20) NOT NULL,
	NEWSTEXT VARCHAR(200),
	NEWSTIME VARCHAR(20),
	NEWSGOODNUMBER VARCHAR(20),
	PRIMARY KEY (NEWSTITLE)
);


CREATE TABLE USER
(
	USERNAME VARCHAR(20) NOT NULL UNIQUE,
	USERPHONENUMBER VARCHAR(20) NOT NULL,
	USERADDRESS VARCHAR(20) NOT NULL,
	USERSEX VARCHAR(5) NOT NULL,
	PRIMARY KEY (USERNAME)
);



